### ISSUE TITLE
can use this great AI to trade on IC MARKETS MT5?DEMO?Ialso have this error

### ISSUE THREAD

**Issue by polonezu1985** [kecoma1/AI_Trading_Bot#1]
Traceback (most recent call last):
  File "C:\Users\Lenovo\anaconda3\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\Lenovo\anaconda3\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Lenovo\Downloads\AI_Trading_Bot-main\bot\Data.py", line 21, in thread_data
    connection, server_socket = socket_ini()
  File "C:\Users\Lenovo\Downloads\AI_Trading_Bot-main\bot\Data.py", line 9, in socket_ini
    server_socket.bind((ADDR, PORT))
OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted

**Comment by kecoma1** [comment]
It seems as if the port you've set is already being used.

And yeah you can use that bot in that Broker. Indeed, in some of my tutorials I use that broker in demo.
